### ISSUE TITLE
Request enhancement to view Crashplan GUI through VNC session

### ISSUE THREAD

**Issue by Nite16** [JrCs/docker-crashplan#19]
Hey - love this Docker container. Using this with no issues on a QNAP NAS device. Works wonderfully. Anyway, one enhancement that would be useful would be to allow access to a GUI through a VNC session without having to use the desktop client.

I've seen this on some other similar containers, but this one is the best and most well-maintained. Just something for consideration. Cheers!

**Comment by JrCs** [comment]
Thanks for you suggestion.

**Comment by tuxpowered** [comment]
Adding VNC would require installing additional libraries to support X-Windows and a lightweight desktop environment, This package is super light weight and is a much better suited to running on a NAS then installing lots of extra software to only be used once or twice.  Admittedly requiring the desktop client to modify the config is an issue, but that issue is really an issue with Crashplan, I would suggest adding a feature request to code42 to officially support headless operations and allow it to be configured, say using a web page/port combination.

**Comment by haysclark** [comment]
@Nite16 This might be a better container for what you want:
https://hub.docker.com/r/gfjardim/crashplan/
